numero = int(input('Insira o numero: '))
a = numero * 0
b = numero * 1
c = numero * 2
d = numero * 3
e = numero * 4
f = numero * 5
g = numero * 6
h = numero * 7
i = numero * 8
j = numero * 9
k = numero * 10
print(f'| {numero} x  0 = {a}')
print(f'| {numero} x  1 = {b}')
print(f'| {numero} x  2 = {c}')
print(f'| {numero} x  3 = {d}')
print(f'| {numero} x  4 = {e}')
print(f'| {numero} x  5 = {f}')
print(f'| {numero} x  6 = {g}')
print(f'| {numero} x  7 = {h}')
print(f'| {numero} x  8 = {i}')
print(f'| {numero} x  9 = {j}')
print(f'| {numero} x 10 = {k}')